### ISSUE TITLE
UWP compiler error

### ISSUE THREAD

**Issue by calebcannon** [KhronosGroup/UnityGLTF#244] opened 2018-09-17 20:35 UTC
https://github.com/KhronosGroup/UnityGLTF/blob/a0201a17abe24aefb48665cc330d5b9243f7693e/UnityGLTF/Assets/UnityGLTF/Scripts/Cache/AssetCache.cs#L97

Should probably be `bufferCacheData.Stream.Dispose();`

**Comment by ivan2007** [comment] 2018-09-18 06:37
This is a duplicate of #240

**Closed** 2018-09-19 18:20 UTC
