### ISSUE TITLE
Google Poly gltf models are white

### ISSUE THREAD

**Issue by Orcha44** [KhronosGroup/UnityGLTF#188] opened 2018-06-05 08:49 UTC
Some "Google Poly" gltf models are white when imported (those without texture). The solution is using the google poly shader when importing.

Example model can be found here - [https://poly.google.com/view/f35tumnmt3N](url)
The shader can be found here - [https://gist.github.com/Orcha44/159cdf2fe4aca86d42574a9753077540](url)

**Comment by naikrovek** [comment] 2018-07-09 16:10
This is the root of the issue I am having as well.  Since it's not new, I won't open a new issue and will instead comment here.

The glTF exporter apparently only supports models with textures.  My models do not have textures and all export without the materials Unity uses.  I am using the standard shader with only albedo and opacity defined.  I understand why the tool can't be expected to support every shader ever, however the standard shader should probably be supported, if it is used.  Unity's FBX exporter handles the materials perfectly, in my limited testing, and I expect conversion from FBX to glTF should work as expected in that case.

Anyway, exporting without support for color-only materials is absolutely useless to me.

**Comment by Grootloops33** [comment] 2018-10-30 15:34
@naikrovek We tested this with some custom models where one used 6 different solid color materials, and the other used a single texture png file, both worked fine, they were exported as obj in maya, and downloaded in unity as gltf through poly.

We however still have this issue with about 90% of the poly models. Even though they work perfectly fine in threeJS.

**Comment by Grootloops33** [comment] 2018-10-30 16:17
> 
> 
> @naikrovek We tested this with some custom models where one used 6 different solid color materials, and the other used a single texture png file, both worked fine, they were exported as obj in maya, and downloaded in unity as gltf through poly.
> 
> We however still have this issue with about 90% of the poly models. Even though they work perfectly fine in threeJS.

We managed to get around this, and got it working by forcing the object to switch to a vertex coloring shader, next step is to detect which model needs which..

**Comment by ericob** [comment] 2019-01-04 22:12
This is a duplicate of #210

**Closed by ericob** 2019-01-04 22:12 UTC
