### ISSUE TITLE
Draco Compression support

### ISSUE THREAD

**Issue by StefanStrategis** [KhronosGroup/UnityGLTF#452] opened 2019-06-17 13:54 UTC
The current library does not support models compressed with the Draco library. Without this feature, it is not possible to load data from Cesium Ion.

**Comment by bghgary** [comment] 2019-06-17 14:18
Dupe of https://github.com/KhronosGroup/UnityGLTF/issues/174

**Closed by bghgary** 2019-06-17 14:18 UTC
