### ISSUE TITLE
Newtonsoft from Unity Asset Store conflict

### ISSUE THREAD

**Issue by amenzies** [KhronosGroup/UnityGLTF#178] opened 2018-05-07 20:10 UTC
I've been running into a couple issues attempting to use the GLTFSerialization.dll in a project that already depends on this version of Netwonsoft on the Unity Asset Store:
https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347

One option would be to remove the Asset Store version of the DLLs from the project and use the ones from the glTF build.  When I attempt this I run into some build issues on UWP/Hololens.  I've followed the guidelines here but am still getting a few errors when I go to create the UWP project from Unity:
https://github.com/KhronosGroup/UnityGLTF/issues/147

I'm sure that I can probably resolve these, but I'm curious what folks think about linking against the Newtonsoft DLLs from the Asset Store rather than the nuget versions.  In my experience the Asset Store versions tend to be the most reliably when building across different platforms.  These also seem like the most likely versions that my already be in use by Unity projects that require JSON for things besides glTF support.

This is easy to work around when building the project yourself so this isn't a big issue.  But I thought I would bring it up for consideration in case anyone else has found themselves needing to do something similar.

**Comment by StephenHodgson** [comment] 2018-05-07 20:14
I think making the json serializer via built I'm Unity utility is a good start and letting people upgrade to newtonsoft is probably a good idea. 

It'll be nice if unity opened up their package manager to include thing's like this so it'll be easier to just pull the package if it's needed.

**Comment by StephenHodgson** [comment] 2018-06-22 14:38
See #60

**Comment by ericob** [comment] 2019-01-04 22:05
Looks like this is a duplicate of #199

**Closed by ericob** 2019-01-04 22:05 UTC
